name: publish

on:
  workflow_dispatch:
    inputs:
      package:
        description: "Name of the crate to publish (e.g., asteria-server)"
        required: false
        default: "all"
      release_type:
        description: "Type of release (minor, major, patch, rc)"
        required: false
        default: "manual"

  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # e.g., v1.0.0
      - "asteria-server-v[0-9]+.[0-9]+.[0-9]+" # e.g., asteria-server-v1.2.3
      - "asteria-client-v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"

jobs:
  publish:
    permissions:
      contents: write

    strategy:
      matrix:
        include:
          - platform: "ubuntu-22.04"
            target: "x86_64-unknown-linux-gnu"
            ext: ""
          - platform: "windows-latest"
            target: "x86_64-pc-windows-msvc"
            ext: ".exe"
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target }}

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev pkg-config libinput-dev

      - name: Cache dependencies
        uses: swatinem/rust-cache@v2

      - name: Determine Package to Build
        id: pkg
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.package }}" != "all" ]]; then
            echo "selected_package=${{ github.event.inputs.package }}" >> $GITHUB_OUTPUT
          else
            # Extract from tag e.g. asteria-server-v1.2.3 → asteria-server
            tag="${GITHUB_REF#refs/tags/}"
            if [[ "$tag" =~ ^(asteria-[a-z]+)-v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
              echo "selected_package=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
            else
              echo "selected_package=all" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Build Release
        shell: bash
        run: |
          mkdir -p release
          pkg="${{ steps.pkg.outputs.selected_package }}"

          if [[ "$pkg" == "all" ]]; then
            cargo build --release --target ${{ matrix.target }}
            cp target/${{ matrix.target }}/release/asteria-* release/
          else
            cargo build --release --package "$pkg" --target ${{ matrix.target }}
            bin_name=$(echo "$pkg" | sed 's/^asteria-//')
            cp target/${{ matrix.target }}/release/$bin_name${{ matrix.ext }} release/${bin_name}-${{ matrix.platform }}${{ matrix.ext }}
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: asteria-${{ matrix.platform }}
          path: release/*

  create-release:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Collect binaries
        run: |
          mkdir -p release
          find artifacts -type f -exec cp {} release/ \;
          ls -la release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
